apiVersion: v1
kind: Secret
metadata:
  name: account-secret
  namespace: leprecon
type: Opaque
data:
  ACCOUNT_HOST: MC4wLjAuMDo4MDgw
  LOG_LEVEL: ZGVidWc=
  ALLOW_ORIGIN: Kg==
  DB_CONN: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQGFjY291bnQtZGF0YWJhc2Utc2VydmljZQ==
  ACCOUNT_CONN: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQGFjY291bnQtZGF0YWJhc2Utc2VydmljZS9hY2NvdW50
  AUTH_HOST: aHR0cHM6Ly9kZXYtMG44eGJzeWlwN29tM3Zhdi5ldS5hdXRoMC5jb20=
  CLIENT_ID_ACCOUNT: OW5lNXJreENKM2o1d0czMjJLM0MxUDNVTDFyVlVsOTU=
  CLIENT_SECRET_ACCOUNT: ZVgwazNIQ0RleUx6Ni1BR2Zsb3VRYTZ4TDV3ZjNyZG5jSU9RRU5IaHNkQ1E5VDZpUl9sTzdqSWpxTkh5cUVFUQ==
  CLIENT_AUD_ACCOUNT: SnVEYW82M3AwQnRIOVcydXVUbFpJeGZnbExUNVdVUnQ=
  VALKEY_CONN: cmVkaXM6Ly9zZXNzaW9uLWRhdGFiYXNlLXNlcnZpY2U6NjM3OQ==
  SUB_NOT_VERIFIED:
