name: leprecon-services
services:
  account:
    image: jarnoweemen/leprecon_account
    container_name: account
    network_mode: host
    build:
      context: .
      dockerfile: src/account/Dockerfile
    env_file: src/account/.env
    environment:
      HOST: ${HOST}
      LOG_LEVEL: ${LOG_LEVEL}
      SESSION_CONN: ${SESSION_CONN}
      AUTH_HOST: ${AUTH_HOST}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      CLIENT_AUD: ${CLIENT_AUD}