apiVersion: v1
kind: ServiceAccount
metadata:
  name: account
  namespace: leprecon
---
apiVersion: v1
kind: Service
metadata:
  name: account
  namespace: leprecon
  labels:
    app: account
    service: account
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: account
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  namespace: leprecon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
      version: v1
  template:
    metadata:
      labels:
        app: account
        version: v1
    spec:
      serviceAccountName: account
      containers:
        - image: ghcr.io/leprec0n/microservices/account:latest
          imagePullPolicy: IfNotPresent
          name: account
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: account-secret
      imagePullSecrets:
        - name: ghcr-login-secret
---
apiVersion: v1
kind: Service
metadata:
  name: account-database-service
  namespace: leprecon
spec:
  selector:
    app: account-database
  ports:
    - port: 5432
      targetPort: account-db-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-database
  namespace: leprecon
spec:
  selector:
    matchLabels:
      app: account-database
  template:
    metadata:
      labels:
        app: account-database
    spec:
      containers:
        - name: account-database
          image: postgres:alpine3.19
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
              name: account-db-port
          envFrom:
            - secretRef:
                name: account-database-secret
