name: Account
run-name: "${{ github.actor }} ran workflow on ${{ github.ref_name }}"
on:
  push:
    branches:
      - '\d+-*'
      - development
    paths:
      - "src/account/**"
  pull_request:
    branches:
      - main
      - development
    paths:
      - "src/account/**"
jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:16.2-alpine3.19
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
      valkey:
        image: valkey/valkey:7.2-alpine3.19
        ports:
          - 6379:6379
    if: github.event.pull_request.base.ref != 'main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Run account tests
        run: cargo test --bin account
        env:
          ALLOW_ORIGIN: http://127.0.0.1:80
          ACCOUNT_CONN: postgresql://postgres:postgres@127.0.0.1/account
          POSTGRES_PASSWORD: postgres
          AUTH_HOST: ${{ secrets.AUTH_HOST }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          CLIENT_AUD: ${{ secrets.CLIENT_AUD }}
          VALKEY_CONN: redis://127.0.0.1:6379
          SUB_NOT_VERIFIED: ${{ secrets.SUB_NOT_VERIFIED }}
          DB_CONN: postgresql://postgres:postgres@127.0.0.1
  build_and_push:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    if: github.event.pull_request.base.ref == 'main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Build docker image
        run: docker build -t 'ghcr.io/${{ github.repository }}/account' -f src/account/Dockerfile .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      - name: Push to GitHub Container Registry
        run: docker push 'ghcr.io/${{ github.repository }}/account:latest'
