name: Development
run-name: "${{ github.actor }} ran workflow on ${{ github.ref_name }}"
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main
jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
  audit:
    needs: lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Run audit
        run: cargo audit
  test:
    needs: audit
    uses: ./.github/workflows/test.yaml
    with:
      test_selection: --workspace
    secrets:
      CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
  build_account:
    if: ${{ github.event_name == 'pull_request' && github.base_ref == 'main' }}
    needs: test
    uses: ./.github/workflows/account.yaml
