name: Development
run-name: "${{ github.actor }} ran workflow on ${{ github.ref_name }}"
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main
jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
  audit:
    needs: lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Run audit
        run: cargo audit
  test:
    needs: audit
    uses: ./.github/workflows/test.yaml
    with:
      test_selection: --workspace
    secrets:
      CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
