name: Development
run-name: '${{ github.actor }} ran workflow on ${{ github.ref_name }}'
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main
jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
  audit:
    needs: lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Run audit
        run: cargo audit
  test:
    needs: audit
    uses: ./.github/workflows/test.yaml
    with:
      test_selection: '--workspace'
  build_and_push:
    needs: test
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'pull_request' && github.base_ref == 'main' }}
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Build docker image
        run: docker build -t 'ghcr.io/${{ github.repository }}' .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ghcr.io
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - name: Push to GitHub Container Registry
        run: docker push 'ghcr.io/${{ github.repository }}:latest'