name: Feature
run-name: "${{ github.actor }} ran workflow on ${{ github.ref_name }}"
on:
  push:
    branches:
      - '\d+-*'
jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
  test:
    uses: ./.github/workflows/test.yaml
    with:
      test_selection: --bin account
    secrets:
      CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
  build_account:
    needs: test
    uses: ./.github/workflows/account.yaml
