name: Feature
run-name: "${{ github.actor }} ran workflow on ${{ github.ref_name }}"
on:
  push:
    branches:
      - '\d+-*'
jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
    with:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  test:
    uses: ./.github/workflows/test.yaml
    with:
      test_selection: --bin account
