name: lint
on:
  workflow_call:
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Run clippy linter
        run: cargo clippy -- -D warnings
      - name: Check if format is needed
        run: cargo fmt --all -- --check