name: lint
on:
  workflow_call:
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Run clippy linter
        run: cargo clippy -- -D warnings
      - name: Check if format is needed
        run: cargo fmt --all -- --check