name: lint
on:
  workflow_call:
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Run clippy linter
        run: cargo clippy -- -D warnings
      - name: Check if format is needed
        run: cargo fmt --all -- --check
